### ISSUE TITLE
I want the cluster no longer split when the size of cluster less then N, what can I do?

### ISSUE THREAD

**Issue by JoinHands** [mapequation/infomap#32] opened 2018-09-07 10:29 UTC

**Comment by danieledler** [comment] 2018-09-10 12:52
Infomap starts by putting each node in their own module and then merge modules, so we have an option `--preferred-number-of-modules <n>` to stop merge modules if it reaches the specified number.

To limit the number of modules from the other direction, you can try increasing the `--markov-time` to make it more costly to move between modules, and thereby find less (larger) modules. It can be combined with the first option though, but note that the first option may give a far from optimal solution.

Does it help?

**Comment by JoinHands** [comment] 2018-09-13 04:16
thanks, I try your suggestion. I have a dataset has 62873846 nodes and 145770116 links. I try use follow configuration:
 -> Configuration: zero-based-numbering
                     markov-time = 2
                     num-trials = 3
                    fast-coarse-tune
                     fast-hierarchical-solution
                    inner-parallelization

the program produce 2230905 top modules，In-depth look at top modules, I find lots of top modules(80%+) only have two or three nodes.  I hope these modules combine to big module or combine themself. what can I do?

**Comment by danieledler** [comment] 2018-09-13 12:14
That was a big network! As long as the nodes in these small modules have links between each other they will probably be combined after increasing the Markov time. The problem is that bigger relevant structures may be combined too, but we have started to explore ways to handle this.

I'm closing the issue for now, but please continue comment on how it goes and feel free to open again if you get any problems with the current setup.

**Closed by danieledler** 2018-09-13 12:14 UTC
